#!/bin/sh

if [ $# != 2 ]; then
  echo "Usage: $(basename "$0") <year-number> <day-number>" >&2
  exit 1
fi
if [ ! -d .git ]; then
  echo "Must be run from root of AoC repository" >&2
  exit 1
fi

year="$1"
day="$2"
name="$(printf "aoc%02d-%02d" "$year" "$day")"
path="$year/$name"
cargo new --bin "$path"
mkdir "$path/input"
